import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components

import ClientLayout from "./ClientLayout";


const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: "--font-jetbrainsMono",

});

export const metadata = {
  title: "Sujith Portfolio",
  description: "Sujith Portfolio Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jetbrainsMono.className} suppressHydrationWarning>
      <body className="antialiased min-h-screen">
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
